spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/itemdb?useSSL=false
    username: root
    password: ""
    driverClassName: com.mysql.jdbc.Driver
  
  jpa:
    generate-ddl: true
    show-sql: true
  
